### ISSUE TITLE
Simulink issue

### ISSUE THREAD

**Issue by cassiodoroVicinetti** [PCMan/gtk3-nocsd#11]
I found an issue with Simulink, installed with MATLAB 2015b (launched with option `-desktop`).

In the main window, when I click "Simulink Library", it prints:

>Can't reload '/opt/MATLAB/R2015b/bin/glnxa64/libmwsl_graphical_classes.so'

When in the file explorer panel I double click a .slx file to open it, it prints:

>Error using axes
>While setting the 'Parent' property of 'Axes':
>Can't load '/opt/MATLAB/R2015b/bin/glnxa64/libmwosgserver.so': dlopen: impossibile caricare altri oggetti con
>un TLS statico
>
>*** MATLAB has encountered a Linux operating system bug; this bug will eventually cause MATLAB to crash. Do
>not repeat the command which produced this error, as doing so might cause an immediate crash. Save your work
>and restart MATLAB now.
>
>Error in msgbox (line 278)
>AxesHandle=axes( ...
>
>Error in errordlg (line 47)
>handle = msgbox(ErrorStringCell,DlgName,'error',Replace);
>
>Error in uiopen (line 194)
>    errordlg(err);

This behaviour appears when I add `LD_PRELOAD` into the `.profile` file or I prepend it directly into the command to launch MATLAB. It doesn't appear if I only have the `70propagate-LD_PRELOAD` file (without `LD_PRELOAD` in `.profile`).

Moreover, when I have `LD_PRELOAD` in `.profile`, even launching MATLAB with `GTK_CSD=1` doesn't work, but the only option is to remove `LD_PRELOAD` from `.profile` and restart the user session.

**Comment by chris-se** [comment]
Without having had a chance to test this myself so far: could you try building `gtk3-nocsd` with
```CFLAGS="-ftls-model=local-dynamic -O2 -g" make```
and try again with it preloaded? That should solve the problem; if it does, I'll add it to the Makefile directly.

**Comment by cassiodoroVicinetti** [comment]
No, it doesn't work, the behaviour is the same.

**Comment by chris-se** [comment]
Could you paste the output of the following?
```readelf -d libgtk3-nocsd.so.0```
(The library should be the compiled one with `-ftls-model=local-dynamic`.)

**Comment by cassiodoroVicinetti** [comment]
```
Dynamic section at offset 0x3548 contains 28 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
 0x000000000000000e (SONAME)             Library soname: [libgtk3-nocsd.so.0]
 0x000000000000000c (INIT)               0xad8
 0x000000000000000d (FINI)               0x255c
 0x0000000000000019 (INIT_ARRAY)         0x2034c0
 0x000000000000001b (INIT_ARRAYSZ)       8 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x2034c8
 0x000000000000001c (FINI_ARRAYSZ)       16 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x1f0
 0x0000000000000005 (STRTAB)             0x510
 0x0000000000000006 (SYMTAB)             0x258
 0x000000000000000a (STRSZ)              573 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x203790
 0x0000000000000002 (PLTRELSZ)           288 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x9b8
 0x0000000000000007 (RELA)               0x808
 0x0000000000000008 (RELASZ)             432 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0x788
 0x000000006fffffff (VERNEEDNUM)         4
 0x000000006ffffff0 (VERSYM)             0x74e
 0x000000006ffffff9 (RELACOUNT)          10
 0x0000000000000000 (NULL)               0x0
```

**Comment by cassiodoroVicinetti** [comment]
The flag has no effect, since the file has the same MD5 checksum as the file built without the flag.

**Comment by chris-se** [comment]
Ok, this is weird. So my initial suspicion because of the error message (`dlopen: impossibile caricare altri oggetti con un TLS statico`) was that because gtk3-nocsd uses TLS (thread local storage) it might be the case that the compiler defaults to static TLS - and that MATLAB doesn't have enough static TLS space available to accommodate both its plugins (e.g. Simulink) and libgtk3-nocsd. So using the `local-dynamic` thread model should take care of this.

Unfortunately, that doesn't appear to be the case here - because the `readelf` output suggests that it isn't using static TLS anyway.

You could try `-ftls-model=global-dynamic` and see if that changes anything (that will definitely change the binary, whether it will help I don't know).

Could you also try to compile the following?
```
int dummy_preloaded_function(void)
{
  return 42;
}
```
with the following command:
```gcc -Wall -O2 -g -Wl,-soname,libdummy-test.so.0 -shared -o libdummy-test.so.0 dummy.c```
and then try to preload it before starting MATLAB?
```LD_PRELOAD=/path/to/libdummy-test.so.0 /path/to/matlab```
and see if the problem also occurs there?

I'll try to reproduce the same thing later once I've installed MATLAB myself. You said it occurred only with Simulink? Which version of Simulink? (I'm not sure I'll have that myself, I'll have to check.)

**Comment by cassiodoroVicinetti** [comment]
>You could try -ftls-model=global-dynamic and see if that changes anything (that will definitely change the binary, whether it will help I don't know).

Mmmm really the binary doesn't change... I'm using this command to compile:
```bash
CFLAGS="-ftls-model=global-dynamic -O2 -g" make
```
and before compiling I always remove the "libgtk3-nocsd.so.0" file. This file always has the same md5 checksum: ```d2cdd51ac989f11633cb9dcebb97a949```

>Could you also try to compile the following?
```C
int dummy_preloaded_function(void)
{
  return 42;
}
```
with the following command:
```bash
gcc -Wall -O2 -g -Wl,-soname,libdummy-test.so.0 -shared -o libdummy-test.so.0 dummy.c
```
and then try to preload it before starting MATLAB?
```bash
LD_PRELOAD=/path/to/libdummy-test.so.0 /path/to/matlab
```
and see if the problem also occurs there?

No, the problem doesn't occur.

>Which version of Simulink?

```
>> ver 
----------------------------------------------------------------------------------------------------
MATLAB Version: 8.6.0.267246 (R2015b)
MATLAB License Number: xxxxxx
Operating System: Linux 4.2.0-1-amd64 #1 SMP Debian 4.2.1-2 (2015-09-27) x86_64
Java Version: Java 1.7.0_60-b19 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
----------------------------------------------------------------------------------------------------
MATLAB                                                Version 8.6         (R2015b)
Simulink                                              Version 8.6         (R2015b)
Embedded Coder                                        Version 6.9         (R2015b)
Fixed-Point Designer                                  Version 5.1         (R2015b)
MATLAB Coder                                          Version 3.0         (R2015b)
Simulink Coder                                        Version 8.9         (R2015b)
Stateflow                                             Version 8.6         (R2015b)
```

**Comment by chris-se** [comment]
> Mmmm really the binary doesn't change... I'm using this command to compile:
> ```CFLAGS="-ftls-model=global-dynamic -O2 -g" make```
> and before compiling I always remove the "libgtk3-nocsd.so.0" file. This file always has the same md5 checksum: d2cdd51ac989f11633cb9dcebb97a949

Oh, did you run `make clean` beforehand? You also need to recompile the object file (not only relink it) to make this work. On my system the following three commands give different binaries:
```
CFLAGS="-ftls-model=global-dynamic -O2 -g" make clean all
CFLAGS="-ftls-model=local-dynamic -O2 -g" make clean all
make clean all
```
Perhaps that's why it didn't work for you before (missing `make clean`) - could you try again with either `local-dynamic` or `global-dynamic` combined with `make clean`?

If that doesn't work, I'll have a look later.

**Comment by cassiodoroVicinetti** [comment]
Whooops I forgot to remove the object file! With `local-dynamic` the binary is still the same, while with `global-dynamic` the binary changes.

Unfortunately I tried the binary with `global-dynamic` but it still doesn't work.

**Comment by chris-se** [comment]
Ok, so while I have access to MATLAB, I don't have Simulink, so I can't really reproduce your issue.

However, could you try the following?

`dummy.c`:
```c
#include <pthread.h>

int dummy_preloaded_function()
{
  static pthread_mutex_t mutex = PTHREAD_MUTEX_INITIALIZER;
  volatile int i;

  pthread_mutex_lock(&mutex);
  i = 42;
  pthread_mutex_unlock(&mutex);

  return i;
}
```
Compile with:
```gcc -Wall -fPIC -pthread -O2 -g -Wl,-soname,libdummy-test.so.0 -shared -o libdummy-test.so.0 dummy.c```
Then try:
```LD_PRELOAD=/path/to/libdummy-test.so.0 /path/to/matlab```
and see if that works.

(I'm trying to isolate the problem using some simple test cases.)

**Comment by chris-se** [comment]
Ok, so while I don't have a solution yet, I do have a way to reproduce it.

`Makefile`:
```make
CFLAGS ?= -O2 -g
CFLAGS += -pthread -fPIC -Wall -ftls-model=initial-exec
#LDLIBS = -ldl

all: libs testbin

libs:
        for i in A B C D E F G H I J K L M N O P Q R S T U V W X Y Z ; do \
                $(CC) $(CFLAGS) $(CPPFLAGS) -DFUNCTION_NAME=dummy_get_int_$$i -c -o libdummy$$i.o x.c ; \
                $(CC) -shared $(CFLAGS) $(LDFLAGS) -Wl,-soname,libdummy$$i.so.0 -o libdummy$$i.so.0 libdummy$$i.o $(LDLIBS) ; \
        done

testbin: testbin.c
        $(CC)  -o testbin testbin.c -Wall -O2 -g -pthread -ldl

clean:
        rm -f *.o *.so.0 testbin *~
```

`x.c`:
```c
static __thread int i = 0;

int FUNCTION_NAME() {
  return i;
}

#define NAME2_HIDDEN(a, b) a ## b
#define NAME2(a, b) NAME2_HIDDEN(a,b)

int NAME2(FUNCTION_NAME, _xx)(int k) {
  i = k;
  return 0;
}
```

`testbin.c`:
```c
#include <dlfcn.h>
#include <stdio.h>
#include <pthread.h>
#include <errno.h>
#include <string.h>
#include <unistd.h>

char alphabet[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

static void *doit(void *dummy)
{
  char buf[] = "./libdummy_.so.0";
  char buf2[] = "dummy_get_int__";
  char buf3[] = "dummy_get_int___xx";
  void *hdl;
  int (*fn)();
  int (*fn2)(int);
  int c;

  for (c = 0; c < sizeof(alphabet) - 1; c++) {
    buf[10] = alphabet[c];
    buf2[14] = alphabet[c];
    buf3[14] = alphabet[c];
    hdl = dlopen(buf, RTLD_NOW | RTLD_GLOBAL);
    if (!hdl) {
      printf("unable to load library %c: %s\n", alphabet[c], dlerror());
      break;
    }
    fn2 = (int (*)())dlsym(hdl, buf3);
    if (!fn2) {
      printf("unable to locate function %s: %s\n", buf3, dlerror());
      break;
    }
    if (fn2(42) != 0) {
      printf("set function call was unsuccessful: %c\n", alphabet[c]);
      break;
    }
    fn = (int (*)())dlsym(hdl, buf2);
    if (!fn) {
      printf("unable to locate function %s: %s\n", buf2, dlerror());
      break;
    }
    if (fn() != 42) {
      printf("get function call was unsuccessful: %c\n", alphabet[c]);
      break;
    }
    printf("done: %c\n", alphabet[c]);
  }

  return dummy;
}

int main()
{
  int r;
  pthread_t thread;

  r = pthread_create(&thread, NULL, doit, NULL);
  if (r < 0) {
    printf("error creating thread: %s\n", strerror(errno));
    return 1;
  }
  (void) pthread_join(thread, NULL);
  return 0;
}
```

If I call that without gtk3-nocsd in `LD_PRELOAD`, it will go up to the letter `M` and fail at the letter `N`. But if I put gtk3-nocsd in `LD_PRELOAD` (even `-ftls-model=global-dynamic`), it will only go up to `L` and fail with letter `M`. This is the same problem you have with Matlab/Simulink - so while I don't have access to the precise software you have, I'm able to reproduce the issue and will try to figure out a solution for it. (I'll probably also add some unit tests for this to make sure this is caught at build time.)

Thanks for your patience.

**Comment by chris-se** [comment]
Ok, so I think I figured out what the problem is: when using LD_PRELOAD, even if the TLS model is dynamic, the dynamic loader doesn't load the library as if it were `dlopen()`d, but as if the program were linked against it - which means that the dynamic thread vector slots for static TLS are used. But since the program itself isn't linked against the preloaded library, this means that an overflow slot has to be used. So whenever you have a program that loads plugins that then use **all** overflow static TLS slots (plugins shouldn't use static TLS model btw., they should use the dynamic one), this will have the problem that the last plugin will not be able to be loaded since the slot is already used. Note that MATLAB plugins are notorious for using static TLS, see http://stackoverflow.com/questions/19268293/matlab-error-cannot-open-with-static-tls , - and since a single extra library such as gtk3-nocsd already causes a problem, loading any additional MATLAB plugin that uses TLS will result in failure anyway, regardless of gtk3-nocsd.

The same problem occurs if multiple libraries are preloaded that fill up the overflow slots, so if you were suddenly to preload 15 libraries with TLS, no binary would execute anymore... (overflow size is 14 by default)

The only solution I see is to explicitly not use the built-in TLS but fall back to traditional pthread functions. This is not optimal, since the pthread functions are slower than the built-in TLS support and they are not quite as easy to use, but they are a complete runtime feature and hence not subject to this issue (they may be subject to memory limitations of pthreads, that's why it's best to allocate only one key and put everything into a single data structure there - that will cause the lowest footprint.)

I've created a patch against current git that *should* solve the issue. I haven't thoroughly tested it, but basic functionality works, so it would be great if you could give it a go:
https://gist.github.com/chris-se/0e82a1d4cff855279ad4
(Just apply it on top of current git.)
If that works for you and doesn't cause any issues with other programs, I'll release a new version with that patch + some other improvements.

(Please compile it normally, e.g. `make clean all`, without any `-ftls-model` flags set - they are not relevant in the new code.)

Thanks for your patience.

**Comment by cassiodoroVicinetti** [comment]
Sorry but yesterday I had no Internet access.

>I've created a patch against current git that *should* solve the issue. I haven't thoroughly tested it, but basic functionality works, so it would be great if you could give it a go:
https://gist.github.com/chris-se/0e82a1d4cff855279ad4
(Just apply it on top of current git.)
If that works for you and doesn't cause any issues with other programs, I'll release a new version with that patch + some other improvements.

It works! Simulink opens as usual with no errors.

>Thanks for your patience.

Well thanks for *your* patience!

**Comment by chris-se** [comment]
Fantastic, then I'll release version 2 this evening with some other improvements + a unit test to make sure this problem you have doesn't happen again. Thanks for testing!
