### ISSUE TITLE
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

### ISSUE THREAD

**Issue by basti122303** [PCMan/gtk3-nocsd#13]
Hello i clone is with git clone and build with  make 

libgtk3-nocsd.so i have copy to gtk3-nocsd.so and create some symlinks
gtk3-nocsd i have copy to /usr/bin/

my installation looks like 
test@jessie-test:/home/develop/gtk3-nocsd/gtk3-nocsd$ echo $GTK_CSD
0
test@jessie-test:/home/develop/gtk3-nocsd/gtk3-nocsd$ echo $LD_PRELOAD
/usr/lib/gtk3-nocsd/libgtk3-nocsd.so
test@jessie-test:/home/develop/gtk3-nocsd/gtk3-nocsd$ ls -la /usr/lib/gtk3-nocsd/
-rwxr-xr-x   1 root root 94808 Nov 26 14:44 gtk3-nocsd.so
lrwxrwxrwx   1 root root    13 Nov 26 14:54 libgtk3-nocsd.so -> gtk3-nocsd.so
lrwxrwxrwx   1 root root    13 Nov 26 14:37 libgtk3-nocsd.so.0 -> gtk3-nocsd.so

test@jessie-test:/home/develop/gtk3-nocsd/gtk3-nocsd$ gtk3-nocsd 
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
/usr/bin/gtk3-nocsd: 88: exec: /.gtk3-nocsd./gtk3-nocsd: not found

thanks for any help!
regards,
basti

**Comment by chris-se** [comment]
First of all, if you already set the `GTK_CSD` and `LD_PRELOAD` environment variables to their correct locations, then you don't need to use `gtk3-nocsd`. That binary is only useful for running individual programs (where you haven't set these environment variables globally) without CSDs; for example, if you don't have `LD_PRELOAD` in your environment, you can do
``` bash
gtk3-nocsd gedit
```
to start `gedit` without CSDs. But the only thing that the `gtk3-nocsd` script does is that it tries to set the environment variables properly. In your case the last error (`88: exec: ...`) just means that calling the script directly doesn't make any sense, because you need to tell it what program to start. (Ok, the error message should probably be better; in the next version I'll make sure that if you call the script without arguments, it will print out some helpful text. I should probably also improve the README file.)

Note that in your case, since you've already set the environment, you don't need it at all - just running e.g. `gedit` should be completely sufficient.

As for the other error messages: they indicate that the script can't find `libgtk3-nocsd.so.0` to preload. The reason for that is that you've installed the script in `/usr/bin`, so it assumes that the library will be found directly by the dynamic linker without an absolute path. But you put the library in the non-standard library directory `/usr/lib/gtk3-nocsd`, which the dynamic linker doesn't find. Since you are using Debian Jessie (I assume at least according to the host name), you can put the library in either `/usr/lib` or `/usr/lib/$ARCH_TRIPLET` (e.g. `/usr/lib/x86_64-linux-gnu` for the `amd64` architecture) in order for the dynamic linker to find it without a path - then the `gtk3-nocsd` script in `/usr/bin` will find it properly. Alternatively, you can build `gtk3-nocsd` with the library path you want to have built in:
``` bash
make clean
make libdir=/usr/lib/gtk3-nocsd
```
and then install the newly generated binary to `/usr/bin`.

But as I said above: in your case, if you already set the environment variables, you don't need to use the `gtk3-nocsd` binary - that's just for the case where you don't want to set the environment variables globally but call specific programs with the library preloaded.

Hope that helps and clarifies things.

**Comment by basti122303** [comment]
Ok I have build an new one and placed it to the right dir.
I started gedit as shown but there is still the "new look and feel" :-( I just want to get the old one back.

**Comment by basti122303** [comment]
![Uploading gedit.jpg…]()

**Comment by basti122303** [comment]
![gedit](https://cloud.githubusercontent.com/assets/4097026/11536066/280dfdd0-9917-11e5-9bb3-cd939e7430b4.jpg)

**Comment by chris-se** [comment]
I think you misunderstand the scope of what gtk3-nocsd does: it makes sure that the window decorations of the window manager are shown, even for Gtk3 applications. That's something that is possible to do generically, without trying to second-guess individual programs. And your screenshot shows that that is what gtk3-nocsd does - you have LXDE's window decorations (I presume) instead of the purely Gtk3 ones.

The problem you are seeing is that gedit has also changed their entire user interface when switching to client side decorations - and that's not something that gtk3-nocsd could easily change back - because it's not just a true/false switch or the like, the code in gedit is completely different. In previous versions, gedit would construct a menu bar and tool bar [in C code] (https://git.gnome.org/browse/gedit/tree/gedit/gedit-window.c?h=gnome-3-10#n1186). That code is completely gone [in the current version of gedit] (https://git.gnome.org/browse/gedit/tree/gedit/gedit-window.c?h=gnome-3-14) - and most of the user interface of gedit is now constructed using [the XML+CSS interface of Gtk3] (https://git.gnome.org/browse/gedit/tree/gedit/resources/ui/gedit-window.ui?h=gnome-3-14#n30), which includes the header bar. This is not something that can be generically changed for all Gtk3 applications, that needs to be changed on the level of individual applications, because everything is application-specific.

In my personal opinion, it only makes sense to use the core GNOME software (gedit, nautilus, etc.) with GNOME, because those projects are so tightly coupled to GNOME itself and the developers there only care about a unified experience within GNOME. If you don't use GNOME but another desktop environment, you're probably better off using different applications, even if they are forks of the GNOME software. Note that the MATE desktop environment is a fork of the GNOME desktop environment (based on GNOME2), and they also forked gedit, they call it pluma. I don't use either, but maybe that might be something you'd be willing to try. (Note that current the MATE version in Jessie is based on Gtk2, not Gtk3.)

Sorry, I can't tell you anything other than that.

**Comment by imambungo** [comment]
I solved it by adding the following line in `.bashrc` file in my home folder:

    export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0

Make sure you have `libgtk3-nocsd.so.0` in `/usr/lib/x86_64-linux-gnu/`

**Comment by LiohMoeller** [comment]
Does not work here:

```
locate libgtk3-nocsd.so.0
/usr/lib64/libgtk3-nocsd.so.0

```
`export LD_PRELOAD=/usr/lib64/libgtk3-nocsd.so.0`

```
flatpak run org.gnome.Evince 
ERROR: ld.so: object '/usr/lib64/libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
```
