### ISSUE TITLE
Not Work in Arch+Xfce

### ISSUE THREAD

**Issue by alireza-amirsamimi** [PCMan/gtk3-nocsd#17]
Hello
I have Archlinux + Xfce
I installed gtk3-nocsd from AUR and added your settings to the bashrc file.
when i run application(for example evince) form terminal, gtk3-nocsd works perfect! but when i run application from menu gtk3-nocsd dosn't work!

**Comment by chris-se** [comment]
I don't use Arch Linux, so I can't tell you anything directly, but my guess is that `.bashrc` is not processed when it comes to the entire X session. Could you try adding those two lines to `.xsessionrc` instead of `.bashrc` (and logging out and in again)? If that works, I'll update the documentation.

**Comment by Xylemon** [comment]
I can confirm the same issue. I swear, there was a package for gtk3-nocsd in the Arch repos a few days ago but I can't seem to find it. I remember it did something different, like place a script in the /etc folder that would load upon boot. I'll attempt the .xsessionrc method in a moment.

**Comment by flexo3001** [comment]
I now maintain a new package because all the nocsd-packages were deleted. You can find it right here
[https://aur.archlinux.org/packages/gtk3-nocsd-git/](url). It doesn't move a script to /etc/profile.d because this would break installations were users have a gnome-session installed and some user want to use this. If .xsessionrc can be used to fixed this i will correct the .install file as well.

**Comment by chris-se** [comment]
FYI: the Debian packaging installs two files in `/etc/X11/Xsession.d/`:
http://sources.debian.net/src/gtk3-nocsd/3-1/debian/extra/51gtk3-nocsd-detect/
http://sources.debian.net/src/gtk3-nocsd/3-1/debian/extra/70gtk3-nocsd-propagate-LD_PRELOAD/
I have no idea if that will work with Arch though, because I have no idea whether the X session startup integration is similar to that of Debian or not. But maybe they can give you a pointer.

**Comment by flexo3001** [comment]
@chris-se Yeah, i saw how you packaged it on Debian. I wanted to adopt it and saw that Arch handles the scripts a bit differently; so i postponed it to when i have more time :). Nevertheless the package basically just compiles and packages the HEAD of master and prints something like: "put 'export....' in your .bashrc"  to the terminal. If the .xsessionrc works for the XFCE-guys i will change this until i find some time to make this like on Debian.
BTW thanks for this great piece of code. It makes all the programs i like usable on i3wm!

**Comment by chris-se** [comment]
Ok, if Arch does the X startup scripts differently, I'm not going to be of much help, sorry. But if you figure out what to do to make it work on Arch, I'll add it to the documentation - leaving this issue open until then.

Btw. should I link the Arch package and mention it in the README file?

**Comment by alireza-amirsamimi** [comment]
I add that 2 bashrc lines to ~/.xsession and problem solved!
thanks for your helps! and thanks for gtk3-nocsd :) this is great!

**Comment by chris-se** [comment]
@flexo3001 I just test-installed Arch in a VM, and you could add the following code to a new file `/etc/X11/xinit/xinitrc.d/30-gtk3-nocsd.sh` with the following contents (and make it executable):

```
#!/bin/bash

if [ -n "${GNOME_DESKTOP_SESSION_ID-}" ] ; then
  # just in case DESKTOP_SESSION wasn't properly set
  _check=gnome
else
  _check="${DESKTOP_SESSION-}"
fi

case "${_check}" in
  gnome|gnome-*|*/gnome|*/gnome-*)
    if [ x"$GTK_CSD" = x"0" ] ; then
      unset GTK_CSD
    fi
    ;;
  *)
    if [ -z "$GTK_CSD" ] ; then
      GTK_CSD=0
    fi
    export GTK_CSD
    if [ x"$GTK_CSD"x = x"0"x ] ; then
      export LD_PRELOAD="libgtk3-nocsd.so.0${LD_PRELOAD:+:$LD_PRELOAD}"
    fi
    ;;
esac

unset _check
```

I've tested this against the GNOME, GNOME classic and Plasma desktops (using SDDM as login manager) and it works as expected: GNOME/GNOME classic always get CSDs, Plasma (non-GNOME) doesn't. You can of course adapt that further to wishes.

Anyway, I've added two hints to the README file of gtk3-nocsd: I mention that people should put the lines into `~/.xsession` instead of `~/.bashrc`, and then I also mention and link the AUR package.

**Comment by flexo3001** [comment]
Oh wait, what. I just woke up and you already wrote the script. Awesome. I added it to the package so the Arch community can use it without having problems with launchers etc. Thank you very much!

**Comment by flexo3001** [comment]
And thank you for mentioning it in the README.
