### ISSUE TITLE
mp3gain crashes with "ASan runtime does not come first in initial library list" after installing libgtk3-nocsd

### ISSUE THREAD

**Issue by mbirth** [PCMan/gtk3-nocsd#36]
After installing libgtk3-nocsd, mp3gain (from https://launchpad.net/~flexiondotorg/+archive/ubuntu/audio) crashes with

    ==14520==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.

Uninstalling libgtk3-nocsd fixes this, but gives a warning about that missing library on every launch (of other tools as well).

Is there a blacklist to add mp3gain to?

**Comment by kilobyte** [comment]
You can't really exclude a library from LD_PRELOAD — it'd require a wrapper that executes every program on its own, only that could apply some sort of blacklist.

That's a problem in mp3gain in that PPA.  Note that mp3gain has been kicked out from both Debian and Ubuntu years ago (last release: wheezy and trusty), and the last version in official repositories still works fine when libgtk3-nocsd is in LD_PRELOAD.  Using ASan in production code is a quirk of that PPA, I'd talk to the guy who maintains it.  Solutions include dropping ASan (no distribution uses it in production for a bunch of reasons), writing a shell wrapper that clears LD_PRELOAD when starting mp3gain, or possibly something else I missed.

In any case, this problem is not related to gtk3-nocsd in any way, any LD_PRELOAD library will suffer this.

**Comment by mbirth** [comment]
Thing is, mp3gain still seems to be the only tool that does proper lossless MP3 normalisation without re-encoding the files. I'd be happy to use an alternative, but I did not yet find one. But yeah, running it as:

    LD_PRELOAD= mp3gain

works for me. Thanks for the info.
