### ISSUE TITLE
LD_PRELOAD 64-bit version?

### ISSUE THREAD

**Issue by sumdog** [PCMan/gtk3-nocsd#5]
I noticed when running wine I get the following:

`
ERROR: ld.so: object '/home/[me]/lib/gtk3-nocsd.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Usage: wine PROGRAM [ARGUMENTS...]   Run the specified program
       wine --help                   Display this help and exit
       wine --version                Output version information and exit
`

wine is a 32-bit executable. Is there a separate variable like LD_PRELOAD that only specifies 64-bit libraries? That might be the cause of some of the other issue tickets.

**Comment by chris-se** [comment]
Well, what you can do is compile both a 32bit and a 64bit version of the library (use the `-m32` compile and linker flag when compiling the 32bit version) and put them into the system paths (on Debian/Ubuntu this would be `/usr/lib/i386-linux-gnu` for 32bit and `/usr/lib/x86_64-linux-gnu` for 64bit - don't know about other distros in that regard) - and just specify `LD_PRELOAD=libgtk3-nocsd.so.0` (no absolute path), and the dynamic linker would automatically pick up the right version. This is only possible for the system paths though; and since you've installed this in your home directory, I don't think there's an easy solution for this.

Unfortunately, there's no way to tell ld.so to suppress warnings with preloads if errors occur, so I don't see any way of getting rid of that warning...

Closing this issue because there's nothing one can do to change gtk3-nocsd to improve this.

**Comment by majenkotech** [comment]
On Debian x64 install `libgtk3-nocsd0:i386` and set `LD_PRELOAD=libgtk3-nocsd.so.0`

It threw me for a while since you install `gtk3-nocsd` normally, but there's no `gtk3-nocsd:i386` since it's just a stub that installs `libgtk3-nocsd0`.

**Comment by hknaydin** [comment]
In fact, unresolved me, still gives the same error.

**Comment by hknaydin** [comment]
can you help me please ? I've done most of the steps.

**Comment by arvesoft** [comment]
I have the same problem

**Comment by ravilov** [comment]
Found another (somewhat quick and dirty) workaround. Simply symlink `/usr/lib/i386-linux-gnu/libgtk3-nocsd.so.0` to the 32-bit version of `libc`. For me it's:

```
# ls -l /usr/lib/i386-linux-gnu/libgtk3-nocsd.so.0 
lrwxrwxrwx 1 root root 37 Sep  4 01:30 /usr/lib/i386-linux-gnu/libgtk3-nocsd.so.0 -> ../../../lib/i386-linux-gnu/libc.so.6
```

`libc` is more than likely to be loaded anyway in most cases.
